const docs = [
  {
    type: 'category',
    label: 'Docs',
    link: { type: 'doc', id: 'docs/readme' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'docs',
      },
    ],
  },
]

const blog = [
  {
    type: 'category',
    label: 'Blog',
    link: { type: 'doc', id: 'blog/readme' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'blog',
      },
    ],
  },
]

// const js = [
//   {
//     type: 'autogenerated',
//     dirName: 'api/js',
//   },
// ]

module.exports = {
  docs,
  blog,
 // js,
}
